account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from account.views import signup

urlpatterns=[
    url(r'^signup/$',signup,name='signup'),
    url(r'^login/$',auth_views.login,{"template_name":'login.html'},name='login'),
    url(r'^logout/$',auth_views.logout,{'next_page':'home'},name='logout'),
]

nidhi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from todo.views import home,todolist

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name='home'),
    url(r'^todos/$',todolist,name='todolist'),
    url(r'^todos/',include('todo.urls',namespace='todo')),
    url(r'account/',include('account.urls')),
]

todo/urls.py
from django.conf.urls  import url
from todo.views import about,contact,todoadd,todolist,tododelete,todoedit

urlpatterns=[
    url(r'^$',todolist,name='todolist'),
    url(r'^about/$',about,name='about'),
    url(r'^contact/$',contact,name='contact'),
    url(r'^add/$',todoadd,name='todoadd'),
    url(r'^edit/(?P<pk>\d+)$',todoedit,name='todoedit'),
    url(r'^delte/(?P<pk>\d+)$',tododelete,name='tododelete'),
    ]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models


# Create your models here.

class Todo(models.Model):
    title=models.CharField(max_length=255)
    description=models.TextField(max_length=255)
    name=models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

class Contact(models.Model):
    name=models.CharField(max_length=255)
    lname=models.CharField(max_length=255)
    email=models.CharField(max_length=255)
    phone=models.CharField(max_length=255)

todo/forms.py
from django import forms
from todo.models import Todo
from todo.models import Contact


class TodoForm(forms.ModelForm):
    class Meta:
        model=Todo
        fields={"title","description","name"}

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields={"name","lname","email","phone"}

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login

# Create your views here.
def signup(request):
    signupform=UserCreationForm(request.POST or None)
    if signupform.is_valid():
        signupform.save()
        username=signupform.cleaned_data.get("username")
        raw_password=signupform.cleaned_data.get("password1")
        user=authenticate(username=username,
        password=raw_password)
        login(request,user)
        return redirect('todolist')
    return render(request,'signup.html',{'form':signupform})

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from todo.models import Todo #conecting databse with views
from todo.forms import TodoForm #connecting user form
from todo.forms import ContactForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request,'about.html')

def contact(request):
    contactform=ContactForm(request.POST or None)
    if contactform.is_valid():
        contactform.save()
        return redirect('home')
    return render(request,'contact.html',{'form':contactform})

@login_required
def todoadd(request):
    todoform=TodoForm(request.POST or None)
    if todoform.is_valid():
        todoform.save()
        return redirect("todolist")
    return render(request,'todoadd.html',{'form':todoform})

@login_required
def todolist(request):
    allfeedback=Todo.objects.all()
    return render(request,'todolist.html',{'todos':allfeedback})

@login_required
def todoedit(request,pk):
    todo = get_object_or_404(Todo,pk=pk)
    todoform = TodoForm(request.POST or None,instance=todo)
    if todoform.is_valid():
        todoform.save()
        return redirect('todolist')
    return render(request,'todoadd.html',{'form':todoform})

@login_required
def tododelete(request,pk):
    todo = get_object_or_404(Todo,pk=pk)
    if request.method=='POST':
        todo.delete()
        return redirect('todolist')
    return render(request,'tododelete.html',{'todo':todo})

templates/about.html
{%extends 'base.html' %}

{%block content %}
<head>
    <style>
        .p1{
        text-align: justify;
        width: 500px;
        margin-left: 500px;
        }
        marquee{
        height: 60px;
        background-color: burlywood;
        font-size: 30px;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        color: white;
        padding-bottom: 30px;
        }
    </style>
</head>
<body>
    <h1 align="center">AboutUs</h1>
    <img style="margin-left:500px;width: 500px;border: 2px solid black;" src="https://image.shutterstock.com/image-photo/about-us-business-team-hands-260nw-446870920.jpg"><br><br>
    <p class="p1">About Us
        LIVEWIRE – A Division of CADD Centre Training Services Pvt Ltd, is an approved Skill Development Partner of National Skill Development Corporation (NSDC). LIVEWIRE promotes a unique combination of technologies that are specific to IT, Computer science, Electronics & Electrical departments. We deal with Emerging technologies 
        like Data science, Machine Learning, IoT, Artificial Intelligence, Blockchain, Full Stack Developer, Cyber security, Automotive Embedded system and many more. LIVEWIRE is present in more than 100 locations in India and over 7 countries.</p>

        <marquee><p>ContactUs:-<i class="fa fa-phone"></i>+91-6262474111&nbsp;<i class="fa fa-envelope"></i>shoppingcart@gmail.com&nbsp;<i class="fa fa-facebook-official" aria-hidden="true"></i>
            ShoppingCart&nbsp;<i class="fa fa-instagram"></i>shopping_Cart&nbsp;<i class="fa fa-twitter"></i>shoppingCart</p></marquee><br><br>

            <br><br>
</body>
{%endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" type="images/icon" href="cart.jpg">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Base</title>
</head>
<body>
    {%include 'nav.html' %}

    {%block content%}
       

    {%endblock%}

    
    {%include 'footer.html' %}
   
</body>
</html>

templates/contact.html
{%extends 'base.html' %}

{%block content %}
<head>
    <style>
        .fm1{
            height: 50px;
            width: 250px;
            text-align: center;
            border-radius: 20px;
        }
      .fm{
        height:30px;
        width:400px;
      }
      
    </style>
</head>
<body>
    
   <br><br>
    <div style="width: 50%; border: 3px solid black; margin-left: 50px;">
        <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=bhawarkua%20square%20near%20apple%20hospital%20452001+(Livewire%20indore)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/sport-gps/">fitness tracker</a></iframe></div>
    </div>
   <div >
       <form  method="POST" style="float: right;margin-top: -600px;margin-right: 250px;">
        <h1 align="center">Contact Us</h1>
        <br>
        {%csrf_token%}
          {{form.as_p}}


           <button style="background-color: coral;" type="submit" class="fm1">Submit</button>

       </form>
   </div><br><br>

    

</body>
{%endblock %}

templates/footer.html
<head>
  <style>
      

        .B1{
            border-radius: 5px;
            margin-left: 5%;
            font-weight: bold;
            color: white;
            background-color: rgb(38, 38, 196);
            border: none;
            height: 52px;
            width: 120px;
        }
        .B1:hover{
            background-color: ghostwhite;
            color: blue;
            border: 2px solid blue;
        }
        .A1{
            font-size: 15px;
            color:rgba(255, 255, 255, 0.616);
            text-decoration: none;
        }
        .A1:hover{
            color: white;
            text-decoration: none;
        }
        .A2{
            color: whitesmoke;
            font-size: 15px;
            font-weight: bold;
            text-decoration: none;
        }
        .A2:hover{
            color: gray;
            text-decoration: none;
        }
        .A3{
            color: darkgray;
            font-family: Verdana, Geneva, Tahoma, sans-serif;
            font-size: 11px;
            text-decoration: none;
        }
        .A3:hover{
            color: black;
            text-decoration: none;
        }
  </style>
</head>




<div style="background-color: rgba(0, 0, 0, 0.884);">
  <div style="float: left; height: 72%; width: 35%;">
  
      <br>
      <br>
      <p style="font-size: 18px; font-weight: bold; margin-left: 15%; color: white;">ABOUT LIVEWIRE</p><br>
      <p style="line-height: 30px; font-size: 15px; margin-left: 15%; color: rgba(255, 255, 255, 0.616);">LIVEWIRE promote niche training in IT, Electronics & <br> Electricals creating experts for emerging technology <br> industries and specialist technology jobs. A part of <br> CADD Centre, which is Asia's largest CAD/CAM/CAE <br> training institute, LIVEWIRE is present in 100 locations <br> across India and 8 International Locations.</p>
      <br>                
  </div>
  <div style="float: right; height: 72%; width: 35%;">
      <br>
      <br>
      <p style="font-size: 18px; font-weight: bold; color: white;">CONTACT INFO</p><br>
      <br>
      <p style="font-weight: normal; font-size: 15px; color:rgba(255, 255, 255, 0.616);"><i style="font-weight: bold; color:rgba(255, 255, 255, 0.616);" class="fa fa-phone" aria-hidden="true"></i>&emsp;&emsp;1800-425-0220</p>
      <br>
      <a class="A1"><i style="color:rgba(255, 255, 255, 0.616);" class="fa fa-envelope" aria-hidden="true"></i>&emsp;&emsp;info@livewireindia.com</a>
      <br>
      <br>
      <p style="line-height: 25px; font-weight: normal; font-size: 15px; color:rgba(255, 255, 255, 0.616);"><i style="color:rgba(255, 255, 255, 0.616);" class="fa fa-map-o" aria-hidden="true"></i>&emsp;&emsp;1st Floor, K.R. Ahamed Sha office complex, No.<br>&emsp;&emsp;&emsp; 25, Dr. Radhakrishnan Salai, Mylapore,<br>&emsp;&emsp;&emsp; Chennai - 600 004,<br>&emsp;&emsp;&emsp; Tamil Nadu, India.</p>

  </div>
  <div style="margin-left: 35%; height: 72%; width: 30%;">
      <br>
      <br>
      <p style="font-size: 18px; font-weight: bold; margin-left: 5%; color: white;">NEWSLETTER</p><br><br>
      <input style="font-size: 16px; border-radius: 5px; margin-left: 5%; border: none; height: 28px; width: 250px;" type="text" placeholder="&emsp;Name">&emsp;
      <br><br>
      <input style="font-size: 16px; border-radius: 5px; margin-left: 5%; border: none; height: 28px; width: 250px;" type="text" placeholder="&emsp;Email address">
      <br>
      <br><br><br><br><br><br><br>
      <button class="B1">SUBMIT</button>
  </div>
</div>
<div style="width: 100%; height: 20%; background-color: rgba(0, 0, 0, 0.938);">

  <div style="float: right;">
      <br>
      
      <a style="text-decoration: none;"><i style="color:white" class="fa fa-facebook-official" aria-hidden="true"></i>&emsp;</a>
      <a style="text-decoration: none;"><i style="color:white; background-color: rgba(0, 0, 0, 0.733) ;" class="fa fa-twitter" aria-hidden="true"></i>&emsp;</a>
      <a style="text-decoration: none;"><i style="color:white; background-color: rgba(0, 0, 0, 0.733) ;" class="fa fa-instagram" aria-hidden="true"></i>&emsp;</a>
      <a style="text-decoration: none;"><i style="color:white; background-color: rgba(0, 0, 0, 0.733) ;" class="fa fa-linkedin" aria-hidden="true"></i>&emsp;</a>
      <a style="text-decoration: none;"><i style="color:white; background-color: rgba(0, 0, 0, 0.733) ;" class="fa fa-youtube-play" aria-hidden="true"></i>&emsp;&emsp;&emsp;&emsp;</a>
  </div>

  <br>
  <a style="margin-left: 5%;" class="A2">Home</a>&emsp;&emsp;
  <a class="A2">About Us</a>&emsp;&emsp;
  <a class="A2">Privacy</a>&emsp;&emsp;
  <a class="A2">Terms & Condition</a><br><br>
  <p style="color: gray; font-family: Arial, Helvetica, sans-serif; font-size: 18px; margin-left: 5%;">LIVEWIRE - All rights reserved © 2019</p>

</div>

templates/home.html
{%extends 'base.html' %}

{%block content %}
<head>
  <style>
    div .row{
        margin-left: 150px;
        margin-right: 0px;
        }
    hr{
        color: red;
      }
    p{
      font-weight: 500;
    }
    .pp{
        text-align: center;
    }
  </style>
</head>

<body>
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://content3.jdmagicbox.com/comp/indore/w5/0731px731.x731.191126172003.l6w5/catalogue/livewire-indore-bhawar-kuan-indore-computer-training-institutes-lt3a5frlr5.jpg?clr=5d2509" class="d-block w-100" style="height: 600px;">
        </div>
        <div class="carousel-item">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJI1LHUasSg4TQpiouHUgTHr-FT-4RThCZDg&usqp=CAU" class="d-block w-100" style="height: 600px;">
        </div>
        <div class="carousel-item">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQREjohA0ChNHspZHyZh6boMFmPPrYqAs-Dsg&usqp=CAU" class="d-block w-100" style="height: 600px;">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div><br>

    <hr>
<div>
    
<h1 align="center">  Welcome to LIVEWIRE</h1>
<p align="center">Education is any kind of knowledge transitioned into learning.</p>
<p class="pp">
  


LIVEWIRE promote niche training in IT, Electronics & Electricals creating experts for emerging technology industries and specialist technology jobs. A part of CADD Centre, which is Asia's largest CAD/CAM/CAE training institute. LIVEWIRE is present in 100 locations across India and 6 Countries.

Learn from the experts
Being the Market leaders with a vast experience of 3 decade, LIVEWIRE courses are designed as per the industry needs.

Guaranteed career growth
The Product Portfolio is filled with technologies that are current and trending. We choose courses that has a high level of scope in the Job market.

100K+ Trained Students
Happy customers builds our strong Alumni network, where they share their industry experience for the next generation.

ISO 29990:2010
Certified for the Quality Training and Competence of learning service providers to all relevant stakeholders
</p>
</div><hr>

<h2 align="center">Trending Courses</h2>
<p align="center">_____</p>
<div class="home">
<div class="row">
    <div class="card" style="width: 18rem;">
        <img  width="250px" height="250px" src="https://content.techgig.com/thumb/msid-79386213,width-1200,height-900,resizemode-4/79386213.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Python</h5>
          <p class="card-text"></p>
          <a href="#" class="btn btn-primary">Enquire Now</a>
        </div>
      </div>
     &nbsp;&nbsp; &nbsp;&nbsp;
      <div class="card" style="width: 18rem;">
        <img  width="250px" height="250px" src="https://miro.medium.com/max/1024/1*3CXBOKNql4qS-lRyHT3pqw.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Machine Learning</h5>
          <p class="card-text"></p>
          <a href="#" class="btn btn-primary">Enquire Now</a>
        </div>
      </div>
      &nbsp;&nbsp; &nbsp;&nbsp;
      <div class="card" style="width: 18rem;">
        <img  width="250px" height="250px"src="https://bernardmarr.com/img/What%20Is%20The%20Importance%20Of%20Artificial%20Intelligence%20(AI).png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Artificial Intellegence</h5>
          <p class="card-text"></p>
          <a href="#" class="btn btn-primary">Enquire Now</a>
        </div>
      </div>
      &nbsp;&nbsp; &nbsp;&nbsp;
      <div class="card" style="width: 18rem;">
        <img width="250px" height="250px" src="https://d35fo82fjcw0y8.cloudfront.net/2019/01/17102218/data-science-in-marketing-post-venn-diagram.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Data Science</h5>
          <p class="card-text"></p>
          <a href="#" class="btn btn-primary">Enquire Now</a>
        </div>
      </div>
</div>
</div> 
<br><br>  
  </body>
{%endblock %}

templates/login.html
{%extends 'base.html'%}


{%block content%}
<head>
    <style>
        form{
            margin-left: 450px;
        }
    </style>
</head>
<form method="post">
    <h1>Login here</h1>
    {%csrf_token%}
    {{ form.as_p }}
    <button type="submit" name="login">Signin</button>
</form>

{%endblock%}

templates/logout.html
{%extends 'base.html'%}


{%block content%}
<h1>You have Successfully logged Out!!</h1>

{%endblock%}

templates/nav.html
<head>
    <style>
        .nv{
            background-color: crimson;
          
        }
        .nav-link{
            color: white;
        }
        .logo{
            width: 200px;
            height: 40px;
        }
        
    </style>
</head>
<body>

<nav class="navbar navbar-dark nv">
    <a class="nav-link" href="http://127.0.0.1:8000/">Home</a>
    <a class="nav-link" href="http://127.0.0.1:8000/todos">All Feedback</a>
    <a class="nav-link" href="http://127.0.0.1:8000/todos/add">Add your feedback</a>
    <a class="nav-link" href="http://127.0.0.1:8000/todos/contact">Contact</a>
    <a class="nav-link" href="http://127.0.0.1:8000/todos/about">About</a>
    <a class="nav-link" href="http://127.0.0.1:8000/account/signup">Signup</a>
    <a class="nav-link" href="http://127.0.0.1:8000/account/login">Signin</a>
    <div>
        {% if user.is_authenticated %}
        <p>Hii,{{user.username}}!!!Welcome<a href="{% url 'logout' %}">Logout</a></p>
        {% endif %}
    </div>
    <a class="nav-link" href="#"><img class="logo" src="https://livewireindia.com/courses/images/livewirelogo.png"></a>
</nav>
</body>

templates/signup.html
{%extends 'base.html'%}

{%block content%}
<head>
    <style>
        form{
            margin-left: 400px;
        }
    </style>
</head>
<form method="post">
    <h1>Register Yourself</h1>
    {%csrf_token%}
    {{ form.as_p }}
    <button type="submit" name="signup">Signup</button>
</form>

{%endblock%}

templates/todoadd.html
{%extends 'base.html'%}

{%block title %}AddData{%endblock%}

{%block content %}

<head>
    <style>
        h1{
            text-align: center;
        }
        form{
            text-align: center;
        }
        form input{
            width:500px;
        }
    </style>
</head>
<br>
<h1>Add your feedback here</h1><br>
<form method="post" style="font-size: 20px;">
    {%csrf_token%}
    {{ form.as_p }}
    <button type="submit" name="savetodo" class="btn-danger" style="border: 1px; border-radius: 10px; font-size: 20px; padding: 5px;">Submit</button>
</form>
<br><br>
{%endblock%}

templates/tododelete.html
{%extends 'base.html'%}

{%block content%}

<form method="post">
    {%csrf_token%}
    <p>Are You Sure?</p>
    <p>Yes Want to Delete "{{todo.title}}"</p>
    <button type="submit" name="tododelete"> Delete</button>

</form>
<br><br>
{%endblock%}

templates/todolist.html
{%extends 'base.html'%}

{%block content%}
<head>
	<style>
		tr,table,th,td{
			border:2px solid crimson;
			width: 200px;
			height: 50px;
		}
		table{
			width: 100%;
			text-align: center;
		}
		button{
			color: white;
			background-color: crimson;
			border-radius: 10px;
			border: 1px solid white ;
		}
	</style>
</head>


<table id="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Name</th>
            <th>CreatedAt</th>
            <th>UpdatedAt</th>
        </tr>
    </thead>
    <tbody>
        {%for todo in todos%}
        <tr>
            <td>{{ todo.title }}</td>
            <td>{{ todo.description }}</td>
            <td>{{ todo.name }}</td>
            <td>{{ todo.created_at }}</td>
            <td>{{ todo.updated_at }}</td>
            <td>
                <a href="{%url 'todo:todoedit' todo.id%}"><button>Update</button></a>
                <a href="{%url 'todo:tododelete' todo.id%}"> <button>Delete</button></a>
            </td>
        </tr>
        {%endfor%}
    </tbody>
</table><br><br>
<button><a id="downLink" onclick="exportF(this)">Download in excel</a></button>
<script>
    function exportF(elem) {
      var table = document.getElementById("table");
      var html = table.outerHTML;
      var url = 'data:application/vnd.ms-excel,' + escape(html); // Set your html table into url 
      elem.setAttribute("href", url);
      elem.setAttribute("download", "export.xls"); // Choose the file name
      return false;
    }
    
</script>
    
{%endblock%}